# External dependencies: CUDA v12.x.x (if NVIDIA's Cuda is installed on the local system: Enables GPU usage, but throws an error if using a different version from cuda 12)
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

LABEL authors="Blazoned"
LABEL owners="Lectorship Data Intelligence Zuyd, Bryan Kroon"
LABEL nl.blazoned.emotionrecognition.service="experimentation"

# Set environment variables:
# - Base directory,
# - Python create binary files (yes or no) (python -b)
# - Python output buffer stream (yes or no) (python -u)
# - Allow deprecated sklearn is important for Talos automl. Leave it enabled!
ENV CONTAINER_HOME=/usr/src/app
ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1
ENV SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True

# Set non-interactive terminal
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Add deadsnakes' ppa for python installation
RUN apt-get update && apt-get upgrade -y && apt-get install -y -q software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa && apt-get update

# Add dependencies required for python, opencv (ffmpeg, libsm6, libxext6) and mlflow (git)
RUN apt-get install -y -q python3.11 python3-pip python3-venv git ffmpeg libsm6 libxext6
RUN python3 -m pip install --upgrade pip

# Copy project to container, build and activate virtual environment, then install requirements
ADD . $CONTAINER_HOME
WORKDIR $CONTAINER_HOME

RUN pip install --upgrade pip
RUN python3 -V
RUN python3 -m venv  .venv

RUN . .venv/bin/activate
RUN pip install --ignore-installed -r $CONTAINER_HOME/requirements.txt

# Execute service
ENTRYPOINT ["python3", "main.py"]
